# Generated by Django 4.2 on 2023-04-24 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование груза'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck', verbose_name='Самосвал'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_model_id',
            field=models.ForeignKey(db_column='truck_model', on_delete=django.db.models.deletion.CASCADE, to='trucks.truckmodel', verbose_name='Модель самосвала'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='max_load_capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальная грузоподъемность (в тоннах)'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование модели самосвала'),
        ),
    ]
