# Generated by Django 4.2 on 2023-04-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_cargotype_remove_cargo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trucks.cargotype', verbose_name='Вид груза'),
            preserve_default=False,
        ),
    ]
